#pragma once

#include "NativeGameplayTags.h"
#pragma region MACROS
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_Active);
#pragma endregion

#pragma region SHARED
#pragma region Abilities
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_HoldInteraction);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_HoldInteraction_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_Death);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_Death_Active);
#pragma endregion

#pragma region Status
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_FreeDragging);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_RailDragging);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Death);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Falling);
#pragma endregion

#pragma region Event
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_AttackHit);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_StopInteraction);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Interaction_Success);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Resonance_CrystalBroken);
#pragma endregion
#pragma endregion

#pragma region MAIN_CHARACTER
#pragma region Abilities
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_Jump);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_Jump_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_Sprint);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_Sprint_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_Crouch);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_Crouch_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_Climb);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_Climb_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_Parry);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_Parry_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_Resonance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_Resonance_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_TapInteraction);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_TapInteraction_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_LowGetOnTop);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_LowGetOnTop_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_LowVault);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_LowVault_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_RecallCompanion);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_RecallCompanion_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_SetCompanionFree);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MainCharacter_SetCompanionFree_Active);
#pragma endregion

#pragma region Status
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_MainCharacter_Crouched);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_MainCharacter_ParryCooldown);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_MainCharacter_ForceMoving);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_MainCharacter_Moving);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_MainCharacter_PreventJumping);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_MainCharacter_PreventDeath);
#pragma endregion

#pragma region Events
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_MainCharacter_StopResonance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_MainCharacter_ActivateResonance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_MainCharacter_EndCrouch);
#pragma endregion

#pragma region Cues
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_MainCharacter_Parry);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_MainCharacter_ParryImpact);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_MainCharacter_ParryCooldownFinished);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_MainCharacter_Death);
#pragma endregion

#pragma region Data
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_MainCharacter_ParryCooldown);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_MainCharacter_CrouchCooldown);
#pragma endregion
#pragma endregion

#pragma region COMPANION
#pragma region Abilities
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_Companion_SoundWave);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_Companion_SoundWave_Active);
#pragma endregion

#pragma region Status
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Companion_Outside);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Companion_Aiming);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Companion_SoundWaveCooldown);
#pragma endregion

#pragma region Event
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Companion_Recall);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Companion_Spawn);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Companion_Despawn);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Companion_ShootSoundWave);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Companion_SwitchSoundWaveTarget);
#pragma endregion

#pragma region Cues
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Companion_SoundWaveCharge);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Companion_SoundWaveAim);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Companion_SoundWaveShoot);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Companion_SoundWaveFinishCooldown);
#pragma endregion

#pragma region Data
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_SoundWaveChargeDuration);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_SoundWaveCooldown);
#pragma endregion
#pragma endregion

#pragma region ENEMIES
#pragma region Abilities
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_EnemyAI_Attack);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_EnemyAI_Attack_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_EnemyAI_CloseAttack);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_EnemyAI_CloseAttack_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_EnemyAI_MantisShift);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_EnemyAI_MantisShift_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_EnemyAI_MantisShift_Nav);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_EnemyAI_MantisShift_Attack);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_EnemyAI_WormRoar);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_EnemyAI_WormRoar_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_EnemyAI_WormDolphinDive);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_EnemyAI_WormDolphinDive_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_EnemyAI_Stun);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_EnemyAI_Stun_Active);
#pragma endregion

#pragma region Status
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_EnemyAI_Stunned);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_EnemyAI_AttackCooldown);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_EnemyAI_Unaware);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_EnemyAI_Suspicious);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_EnemyAI_Alerted);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_EnemyAI_Hunting);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_EnemyAI_WormDolphinDiveCooldown);
#pragma endregion

#pragma region Events
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_EnemyAI_Hit);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_EnemyAI_WormRoar);
#pragma endregion

#pragma region Cues
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_EnemyAI_WormRoar);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_EnemyAI_Stun);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_EnemyAI_Mantis_Shift_Loop);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_EnemyAI_Mantis_Shift_Burst);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_EnemyAI_AttackFeedback);
#pragma endregion

#pragma region Data
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_EnemyAI_AttackCooldown);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_EnemyAI_StunCooldown);
#pragma endregion
#pragma endregion

#pragma region INPUTS
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_InputReleased_Crouch);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_InputReleased_Sprint);
#pragma endregion

#pragma region COLLISIONS
#pragma region Events
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Collision_Activate);
#pragma endregion
#pragma endregion

#pragma region INTERACTIONS
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Interact_Tap);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Interact_Deflect);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Interact_Projectile);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Interact_Hold_DragFree);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Interact_Hold_DragRail);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Interact_Resonance);
#pragma endregion

#pragma region UI
#pragma region Layers
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Game);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Menu);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Window);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Modal);
#pragma endregion
#pragma region Actions
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Action_Settings);
#pragma endregion
#pragma endregion

#pragma region AUDIO
#pragma region States
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Audio_State_MainMenu);
#pragma endregion
#pragma endregion

#pragma region UTILS
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Climb);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Counterweight);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AttackHitBox);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ParrySphere);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MainCharacter);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Enemy);

#pragma region Cues
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_GroundDebris);
#pragma endregion 
#pragma endregion