;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/StillHear
DestinationPath=Content/Localization/StillHear
ManifestName=StillHear.manifest
ArchiveName=StillHear.archive
CulturesToGenerate=en
CulturesToGenerate=it

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=StillHear.csv

