;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Flow.ID.Repeater",NewTagName="Flow.ID.Trigger.Repeater")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Audio.State.Begin",DevComment="")
+GameplayTagList=(Tag="Audio.State.Cave",DevComment="")
+GameplayTagList=(Tag="Audio.State.Combat",DevComment="")
+GameplayTagList=(Tag="Audio.State.Cutscene",DevComment="")
+GameplayTagList=(Tag="Audio.State.Diapason",DevComment="")
+GameplayTagList=(Tag="Audio.State.Guardian",DevComment="")
+GameplayTagList=(Tag="Audio.State.MainMenu",DevComment="")
+GameplayTagList=(Tag="Audio.State.OutsideTemple",DevComment="")
+GameplayTagList=(Tag="Audio.State.Portal",DevComment="")
+GameplayTagList=(Tag="Audio.State.RevelationTemple",DevComment="")
+GameplayTagList=(Tag="Audio.State.Stealth",DevComment="")
+GameplayTagList=(Tag="Audio.State.StealthTemple",DevComment="")
+GameplayTagList=(Tag="Audio.State.Temple",DevComment="")
+GameplayTagList=(Tag="Audio.State.TowerOst",DevComment="")
+GameplayTagList=(Tag="Audio.State.Worms",DevComment="")
+GameplayTagList=(Tag="Data.BaseSpeed",DevComment="")
+GameplayTagList=(Tag="Data.SpeedMultiplier",DevComment="")
+GameplayTagList=(Tag="Event.Abilities",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.Collision.Activate",DevComment="")
+GameplayTagList=(Tag="Event.Companion.Despawn",DevComment="")
+GameplayTagList=(Tag="Event.Companion.Recall",DevComment="")
+GameplayTagList=(Tag="Event.Companion.Spawn",DevComment="")
+GameplayTagList=(Tag="Event.InputReleased.Crouch",DevComment="")
+GameplayTagList=(Tag="Event.InputReleased.Sprint",DevComment="")
+GameplayTagList=(Tag="Flow.ID.CinematicDoor",DevComment="")
+GameplayTagList=(Tag="Flow.ID.CinematicFInal",DevComment="")
+GameplayTagList=(Tag="Flow.ID.CinematicGuardian",DevComment="")
+GameplayTagList=(Tag="Flow.ID.CinematicTowerTransition",DevComment="")
+GameplayTagList=(Tag="Flow.ID.Enemy.Mantis",DevComment="")
+GameplayTagList=(Tag="Flow.ID.Enemy.Worm",DevComment="")
+GameplayTagList=(Tag="Flow.ID.MainMenu",DevComment="")
+GameplayTagList=(Tag="Flow.ID.Root",DevComment="")
+GameplayTagList=(Tag="Flow.ID.TempleCinematic",DevComment="")
+GameplayTagList=(Tag="Flow.ID.Trigger",DevComment="")
+GameplayTagList=(Tag="Flow.ID.Trigger.Crouch",DevComment="")
+GameplayTagList=(Tag="Flow.ID.Trigger.EnemyTutorial",DevComment="")
+GameplayTagList=(Tag="Flow.ID.Trigger.EnemyWorms",DevComment="")
+GameplayTagList=(Tag="Flow.ID.Trigger.HintRunJump",DevComment="")
+GameplayTagList=(Tag="Flow.ID.Trigger.Jump",DevComment="")
+GameplayTagList=(Tag="Flow.ID.Trigger.PassCheck",DevComment="")
+GameplayTagList=(Tag="Flow.ID.Trigger.Push",DevComment="")
+GameplayTagList=(Tag="Flow.ID.Trigger.Repeater",DevComment="")
+GameplayTagList=(Tag="Flow.ID.Trigger.Resonance",DevComment="")
+GameplayTagList=(Tag="Flow.ID.Trigger.RunJump",DevComment="")
+GameplayTagList=(Tag="Flow.ID.Trigger.SoundWave",DevComment="")
+GameplayTagList=(Tag="Flow.Trigger.In",DevComment="")
+GameplayTagList=(Tag="Flow.Trigger.Out",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.EnemyAI",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.EnemyAI.Attack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.EnemyAI.Attack.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.Climb",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.Climb.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.Crouch",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.Crouch.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.Jump",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.Jump.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.LowGetOnTop",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.LowGetOnTop.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.LowVault",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.LowVault.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.Parry",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.Parry.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.RecallCompanion",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.RecallCompanion.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.SetCompanionFree",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.SetCompanionFree.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.Sprint",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MainCharacter.Sprint.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue.MainCharacter.Parry",DevComment="")
+GameplayTagList=(Tag="Status.Companion.Outside",DevComment="")
+GameplayTagList=(Tag="Status.MainCharacter.Crouched",DevComment="")
+GameplayTagList=(Tag="Status.MainCharacter.InAir",DevComment="")
+GameplayTagList=(Tag="UI.Action.BackToMenu",DevComment="")
+GameplayTagList=(Tag="UI.Action.Continue",DevComment="")
+GameplayTagList=(Tag="UI.Action.Extra",DevComment="")
+GameplayTagList=(Tag="UI.Action.Load",DevComment="")
+GameplayTagList=(Tag="UI.Action.NewGame",DevComment="")

